// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Gw-SA6wvoMtzRFeM4b2x1D_JbZbueqk',
    appId: '1:150931280899:web:84e5b798b0004e44d0ea36',
    messagingSenderId: '150931280899',
    projectId: 'whatsapp-5a303',
    authDomain: 'whatsapp-5a303.firebaseapp.com',
    databaseURL: 'https://whatsapp-5a303-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-5a303.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRWWlIXXWmKH-rwRdEi7BWZmAw2oeNrPg',
    appId: '1:150931280899:android:f6225262729c1a0bd0ea36',
    messagingSenderId: '150931280899',
    projectId: 'whatsapp-5a303',
    databaseURL: 'https://whatsapp-5a303-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-5a303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGte_yKpQPDlvaz0LDNXtzeaZEdVJdmAc',
    appId: '1:150931280899:ios:768c2d6f2f4e31c3d0ea36',
    messagingSenderId: '150931280899',
    projectId: 'whatsapp-5a303',
    databaseURL: 'https://whatsapp-5a303-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-5a303.appspot.com',
    androidClientId: '150931280899-3o7l7kkje31aoodhl594qe9mj9ki4ftd.apps.googleusercontent.com',
    iosClientId: '150931280899-unq3u9tl13upa9rdt0m9nq5cskbfrvgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.provider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGte_yKpQPDlvaz0LDNXtzeaZEdVJdmAc',
    appId: '1:150931280899:ios:768c2d6f2f4e31c3d0ea36',
    messagingSenderId: '150931280899',
    projectId: 'whatsapp-5a303',
    databaseURL: 'https://whatsapp-5a303-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-5a303.appspot.com',
    androidClientId: '150931280899-3o7l7kkje31aoodhl594qe9mj9ki4ftd.apps.googleusercontent.com',
    iosClientId: '150931280899-unq3u9tl13upa9rdt0m9nq5cskbfrvgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.provider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Gw-SA6wvoMtzRFeM4b2x1D_JbZbueqk',
    appId: '1:150931280899:web:823c0b505c0ee5e7d0ea36',
    messagingSenderId: '150931280899',
    projectId: 'whatsapp-5a303',
    authDomain: 'whatsapp-5a303.firebaseapp.com',
    databaseURL: 'https://whatsapp-5a303-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-5a303.appspot.com',
  );
}
